apiName: "IPSEN3-Lions-API"

#databaseURL: "145.97.16.190:3306"
#databaseUser: "IPSEN3G1"
#databasePwd: "IPSEN3G1"
#databaseName: "IPSEN3G1"

databaseURL: "localhost:3306"
databaseUser: "IPSEN3"
databasePwd: "IPSEN3"
databaseName: "IPSEN3G1"

assets:
  mappings:
      /includes: /
  overrides:
    /: ../Lions-Client/public_html/


      
server:
  rootPath: /IPSEN3-Lions-API/*
  adminContextPath: /admin