apiName: "IPSEN3-Lions-API"

databaseURL: "127.0.0.1:8889"
databaseUser: "root"
databasePwd: "root"
databaseName: "mydb"

assets:
  mappings:
      /includes: /
  overrides:
    /: ../Lions-Client/public_html/


      
server:
  rootPath: /api/*
  adminContextPath: /admin